version: "3"

services:
  radar:
    build: .
    container_name: pharma-radar
    volumes:
      - .:/app
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}

  dashboard:
    build: .
    command: streamlit run dashboard/app.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
